


## 2. Geoidundulation --------------------------------------------------------------------------------------------------


#' just a test still


#' Elevation data might be in a different reference system than DHHN16 which is used since 2019. To convert the heights 
#' from another vertical crs to DHHN16 a geoidmodel (raster) needs to be used. 


### Preprocess the geoid ----

# Read the geoid model (TIFF file)
#geoid <- rast("C:/Users/NBW-Ebenbeck_J/Downloads/quasigeoid.geo89.de/quasigeoid/de/windows/geotiff/GCG2016v2023.tif")
#plot(geoid)

#poly <- as.polygons(geoid, values = F, aggregate = T) 
#poly

#poly_merged <- terra::aggregate(poly)
#mapview(poly_merged)
#' Interpolate for higher resolution and smoother results:

# Create empty target raster
#r <- rast(x = ext(geoid), resolution = 100, crs = terra::crs(geoid))

#' interpolate grid:
#y <- resample(geoid, r, method = "bilinear")

#' reproject geoid to match point cloud:
#geoid_UTM <- project(y, "epsg:25832")


#' export raster:
#writeRaster(y, "C:/Users/NBW-Ebenbeck_J/Downloads/quasigeoid.geo89.de/quasigeoid/de/windows/geotiff/GCG2016v2023_100m.tif")

### Perform the geoidundulation on ALS data ----

#ALS <- readALSLAS("D:/ALS 2017/NPV_00551.laz")
#ALS
#crs(ALS) <- "EPSG:25833"

#ALS_trans <- st_transform(ALS, "epsg:25832")
#ALS_trans@data

#ALS_Geoid <- merge_spatial(ALS_trans, y, "Geoidundulation")
#ALS_Geoid@data

#test <- readALSLAS("D:/ALS 2012/UTM32/spur00001_UTM.laz")




## 7. Accurracy assessment ---------------------------------------------------------------------------------------------



### 7.1. Prepare GCPs ----


#' This function takes a list of txt-files generated by the CloudCompare point picking tool and converts them to a single 
#' geopackage. The points represent GCPs sampled in the point clouds within the pre-defined AOIs.

prepare_GCPs <- function(input_path, output_path, filename, polygons){
  
  #' list all txt files generated by CloudCompare point picking tool:
  file_list <- list.files(input_path, pattern = "\\.txt$", full.names = T)
  
  #' process the data:
  
  data <- lapply(file_list, read.table, header = F, sep = ",") %>%  # Read all files into a list 
    bind_rows() %>%     #' combine tha datasets
    rename_with(~ c("Description", "X", "Y", "Z")) %>%      #' rename columns 
    st_as_sf(coords = c("X", "Y"), crs = "EPSG:25832", remove = F) %>%      #' convert to spatial data
    st_join(AOIs["name"]) %>%       #' overlay GCPs with polygons to get info on AOI
    rename(AOI = name) %>% 
    group_by(AOI) %>% 
    mutate(ID = paste0(substr(AOI, 1, 3), "_", row_number()),  .before = everything()) %>%  #' generate an unique ID for all GCPs
    ungroup()
  
  #' export to disk:
  st_write(data, paste0(output_path, "/", filename, ".gpkg"), append = F) 
  
  return(data)
  
}


### 7.2. Merge GCPs with reference data ----


#' Merges the GCPs that should be tested (of one year) with their corresponding GCPs of the LDBV ALS data

merge_GCPs <- function(gcp_data_test, gcp_data_ref, export = F, filename = F, output_path = F) {
  
  #' calculate indices describing the nearest feature:
  nearest_indices <- st_nearest_feature(gcp_data_ref, gcp_data_test)
  
  # Add corresponding matches from the test data to the reference data
  gcp_data_ref$matchedID <- gcp_data_test$ID[nearest_indices]
  
  # Join attributes
  gcp_data_test_ref <- left_join(as.data.frame(gcp_data_test), as.data.frame(gcp_data_ref), 
                                 by = c("ID" = "matchedID"), suffix = c("", "_ref"), keep = F) %>%
    rename("X_obs" = "X", "Y_obs" = "Y", "Z_obs" = "Z") %>% 
    mutate(deltaX = X_obs - X_ref, 
           deltaY = Y_obs - Y_ref,
           deltaH = sqrt(deltaX^2 + deltaY^2),  # Horizontal Error
           deltaZ = Z_obs - Z_ref) %>% 
    filter(abs(deltaX) < 5,
           abs(deltaY) < 5,
           abs(deltaZ) < 5) %>%        #' filter points that are less the 5 m apart to their match
    select(ID, Description, AOI, X_obs, Y_obs, Z_obs, X_ref, Y_ref, Z_ref, deltaX, deltaY, deltaH, deltaZ, geom) %>% 
    st_as_sf() 
  
  if (export == T) {
    #' export to disk:
    st_write(gcp_data_test_ref, paste0(output_path, "/", filename, ".gpkg"), append = F) 
  }
    
  return(gcp_data_test_ref)

}


### 7.3. Generate boxplots ----


#' generates boxplots showing the difference between the GCPs from the test data to the reference data in X, Y and Z 
#' dimension per AOI.

aa_create_boxplots <- function(gcp_data, export = F, filename, output_path){
  
  #' re-format data for better visualization:
  data <- gcp_data %>% pivot_longer(cols = c(deltaX, deltaY, deltaZ), names_to = "Direction", values_to = "Difference") %>% 
    mutate(Direction = recode(Direction, "deltaX" = "X", "deltaY" = "Y", "deltaZ" = "Z"))
  
  #' generate the plot:
  bplot <- ggplot(data = data, aes(y = Difference, x = AOI)) +
    geom_hline(yintercept = 0, color = "darkgrey", linewidth = 0.5) +
    geom_point(position = position_jitter(width = 0.1), shape = 1, size = 0.1, color = "blue") +
    geom_boxplot(outliers = F, color = "black", fill = NA, width = 0.2) +
    facet_wrap(vars(Direction), nrow = 3, ncol = 1, shrink = F) + 
    labs (y = "Difference (meter)") +
    theme_bw() +
    theme(
      axis.title.x = element_blank(),
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)
    )
  
  plot(bplot)
  
  if (export == T) {
    #' export the plot to disk:
    ggsave(filename = paste0(filename, ".png"),
           plot = bplot, device = "png",
           path = output_path,
           width = 200, height = 200, units = "mm", dpi = 300)
  }
  
} 


### 7.4. Calculate accurracy metrics ----


aa_metrics <- function(gcp_data, export = F, filename, output_path){
  
  #' Convert data to long format for easier processing
  df_long <- gcp_data %>%
    st_drop_geometry() %>% 
    select(deltaX, deltaY, deltaZ, deltaH) %>%
    pivot_longer(cols = everything(), names_to = "direction", values_to = "error")
  
  #' Compute accuracy metrics using yardstick
  summary_table <- df_long %>%
    group_by(direction) %>%
    summarise(
      RMSE = round(rmse_vec(rep(0, n()), error), 3),
      MAE = round(mae_vec(rep(0, n()), error), 3),
      Bias = round(mean(error), 3),
      SD = round(sd(error), 3)
    ) %>%
    mutate(direction = recode(direction, "deltaX" = "X", "deltaY" = "Y", "deltaZ" = "Z", "deltaH" = "H"))

  #' Export table to csv
  if (export == T) {
    write.csv2(summary_table, file = paste0(output_path, "/", filename, ".csv"), row.names = F, dec = ".")
  }
  
  #' Print the final table
  return(summary_table)
  
}



## 8. Ground point classification --------------------------------------------------------------------------------------


catalog_classify_ground <- function(lascatalog, algorithm = lidR::csf(), last_returns = T, output_path, 
                                    filename_convention = "{ORIGINALFILENAME}", parallel = FALSE, n_cores =2) {
  
  #' apply options to lascatalog
  opt_output_files(lascatalog) <- paste0(output_path, "/", filename_convention)
  opt_laz_compression(lascatalog) <- TRUE
  opt_chunk_buffer(lascatalog) <- 10
  opt_chunk_size(lascatalog) <- 0
  
  #' plan parallel processing
  if (parallel == TRUE) {
    plan(multisession, workers = n_cores)
    message(paste("Parallel processing will be used with", n_cores, "cores"))
  } else {
    warning("No parallel processing in use", call. = F, immediate. = T)
  }
  
  #' classify lascatalog:
  classified_catalog <- classify_ground(lascatalog, algorithm = algorithm, last_returns = last_returns)
  return(classified_catalog)
}
  




## 11. DTM creation ----------------------------------------------------------------------------------------------------


#' creates DTMs from a lascatalog. The dtms are exported to disc in tiles and optional, the results can be mosaiced. 

catalog_dtm <- function(lascatalog, resolution = 1, output_path, filename_convention, mosaic_result = F, 
                        mosaic_name = NULL, parallel = FALSE, n_cores = 2){
  
  #' apply options to lascatalog
  opt_output_files(lascatalog) <- paste0(output_path, "/", filename_convention)
  opt_chunk_buffer(lascatalog) <- 10
  opt_chunk_size(lascatalog) <- 0
  opt_select(lascatalog) <- "xyzc" #' select only relevant attributes
  opt_filter(lascatalog) <- "-keep_class 2" #' select only ground points
  
  #' function to compute the dtm:
  derive_dtm = function(las){
    dtm <- lidR::rasterize_terrain(las, res = resolution, algorithm = tin())
    #return(dtm)
  }
  
  #' plan parallel processing
  if (parallel == TRUE) {
    plan(multisession, workers = n_cores)
    message(paste("Parallel processing will be used with", n_cores, "cores"))
  } else {
    warning("No parallel processing in use", call. = F, immediate. = T)
  }
  
  #' apply function to lascatalog:
  catalog_dtm = catalog_map(lascatalog, derive_dtm)
  
  #' mosaic the resulting dataset if wanted:
  if (mosaic_result == TRUE) {
    message("starting mosaicing the resulting tiles...")
    #' list of all generated tif files:
    tif_files <- list.files(output_path, pattern = "\\.tif$", full.names = TRUE)
    #' read in all rasters into a spatial raster collection:
    raster_list <- sprc(tif_files)
    #' mosaic the files:
    raster_mosaic <- terra::mosaic(raster_list)
    #' export to disk:
    terra::writeRaster(raster_mosaic, paste0(output_path, "/", mosaic_name, ".tif"), filetype = "GTiff", 
                       overwrite = TRUE, wopt= list(datatype = "FLT4S", filetype = "GTiff", todisk = TRUE, 
                                                    gdal=c("COMPRESS=LZW", "TILED=YES")))
  }
  
  return(catalog_dtm)

}
